### PR TITLE
Update utils.ISO8601

### LINKED ISSUE #15: Embed timestamp error - not a valid ISO8601 datetime.
**Describe the bug**
If I want to add a timestamp (where I can only use datetime.datetime or Embed.Empty), guilded.py throws an error at me that it's not a valid ISO8601 datetime. 

**To Reproduce**
Create an embed and add a timestamp:
```python
embed = guilded.Embed(
            title="Title",
            description="Description"
        )
embed.timestamp = datetime.datetime.utcnow()
await ctx.send(embed=embed)
```

**Expected behavior**
I would expect that guilded.py would convert the timestamp to ISO8601 for me since I cannot use an ISO8601 str instead.

**Actual behavior**
I receive a TypeError and the message gets sent with a timestamp (not sure if it is correct, the embed shows the correct date at least)
<details>
  <summary>Traceback (Note in the screenshot that I send an embed on an exception, so the traceback is doubled)</summary>

```
Traceback (most recent call last):
  File "/root/.local/lib/python3.9/site-packages/guilded/client.py", line 231, in _run_event
    await coro(*args, **kwargs)
  File "/Pumpkin/modules/base/errors/module.py", line 34, in on_error
    await bot_log.error(None, None, traceback=tb)
TypeError: error() missing 1 required positional argument: 'message'
Task exception was never retrieved
future: <Task finished name='Task-1' coro=<Client.start() done, defined at /root/.local/lib/python3.9/site-packages/guilded/client.py:277> exception=GuildedException(TypeError('2021-09-04T15:17:24.372247+00:00 is not a valid ISO8601 datetime.'))>
Traceback (most recent call last):
  File "/root/.local/lib/python3.9/site-packages/guilded/utils.py", line 75, in ISO8601
    return datetime.datetime.strptime(string, '%Y-%m-%dT%H:%M:%S.%fZ')
  File "/usr/local/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2021-09-04T15:17:24.372247+00:00' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/lib/python3.9/site-packages/guilded/gateway.py", line 173, in received_event
    await event
  File "/root/.local/lib/python3.9/site-packages/guilded/gateway.py", line 239, in ChatMessageCreated
    message = self._state.create_message(channel=channel, data=data, author=author, team=team)
  File "/root/.local/lib/python3.9/site-packages/guilded/http.py", line 727, in create_message
    return ChatMessage(state=self, **data)
  File "/root/.local/lib/python3.9/site-packages/guilded/message.py", line 277, in __init__
    self.content = self._get_full_content(data)
  File "/root/.local/lib/python3.9/site-packages/guilded/message.py", line 424, in _get_full_content
    self.embeds.append(Embed.from_dict(msg_embed))
  File "/root/.local/lib/python3.9/site-packages/guilded/embed.py", line 191, in from_dict
    self._timestamp = utils.ISO8601(data['timestamp'])
  File "/root/.local/lib/python3.9/site-packages/guilded/utils.py", line 81, in ISO8601
    raise TypeError(f'{string} is not a valid ISO8601 datetime.')
TypeError: 2021-09-04T15:17:24.372247+00:00 is not a valid ISO8601 datetime.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.local/lib/python3.9/site-packages/guilded/client.py", line 283, in start
    await self.connect()
  File "/root/.local/lib/python3.9/site-packages/guilded/client.py", line 372, in connect
    await asyncio.gather(
  File "/root/.local/lib/python3.9/site-packages/guilded/client.py", line 346, in listen_socks
    await ws.poll_event()
  File "/root/.local/lib/python3.9/site-packages/guilded/gateway.py", line 186, in poll_event
    await self.received_event(msg.data)
  File "/root/.local/lib/python3.9/site-packages/guilded/gateway.py", line 181, in received_event
    raise exc from e
guilded.errors.GuildedException: 2021-09-04T15:17:24.372247+00:00 is not a valid ISO8601 datetime.
Ignoring exception in on_command_error:
Traceback (most recent call last):
  File "/root/.local/lib/python3.9/site-packages/guilded/utils.py", line 75, in ISO8601
    return datetime.datetime.strptime(string, '%Y-%m-%dT%H:%M:%S.%fZ')
  File "/usr/local/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2021-09-04T15:17:25.902639+00:00' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/lib/python3.9/site-packages/guilded/client.py", line 231, in _run_event
    await coro(*args, **kwargs)
  File "/Pumpkin/modules/base/errors/module.py", line 67, in on_command_error
    await ctx.send(embed=embed)
  File "/root/.local/lib/python3.9/site-packages/guilded/abc.py", line 188, in send
    return Message(state=self._state, channel=self, data=payload, author=author)
  File "/root/.local/lib/python3.9/site-packages/guilded/message.py", line 277, in __init__
    self.content = self._get_full_content(data)
  File "/root/.local/lib/python3.9/site-packages/guilded/message.py", line 424, in _get_full_content
    self.embeds.append(Embed.from_dict(msg_embed))
  File "/root/.local/lib/python3.9/site-packages/guilded/embed.py", line 191, in from_dict
    self._timestamp = utils.ISO8601(data['timestamp'])
  File "/root/.local/lib/python3.9/site-packages/guilded/utils.py", line 81, in ISO8601
    raise TypeError(f'{string} is not a valid ISO8601 datetime.')
TypeError: 2021-09-04T15:17:25.902639+00:00 is not a valid ISO8601 datetime.
```
</details>

**Screenshot**

Screenshot_20210904_171741

**Environment**
 - Host OS: Fedora 34
 - Docker image: python:3.9.5-slim
 - Python version: 3.9.5
 - Library version: 4a64e136f69455a0a410ac139b4315d9ff9bb543

### PR DESCRIPTION
**Pull request by anytarseir67**
fixes #15

### CODE REVIEW

**Comment by shayypy** [comment]
Has this been tested against timestamps that Guilded will actually send? They end a little bit differently and I can’t remember if this method covers that.

**Comment by anytarseir67** [comment]
it already handles timestamps from Guilded, so this only affects timestamps from a datetime.

**Comment by shayypy** [comment]
Yes, but you removed a second `strptime` that IIRC I added for edge cases from Guilded (in which no microsecond is included).

**Comment by anytarseir67** [comment]
as far as i can tell, the first one handles everything from guilded, i tested this out for a while and i never got any errors.

**Comment by shayypy** [comment]
Yeah, hence edge case. I should prefer it stays in, and `fromisoformat` being another layer down.

**Comment by anytarseir67** [comment]
readded it.

**Comment by shayypy** [comment]
Thanks

**Pull request merged**
